apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: workload-availability-og
  namespace: openshift-workload-availability
spec:
  targetNamespaces:
    - openshift-workload-availability