apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: node-maintenance
  namespace: openshift-workload-availability
spec:
  channel: stable
  name: node-maintenance-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic